### ISSUE TITLE
Permissions 

### ISSUE THREAD

**Issue by NiceATC** [PhoenixPlays/Ticket-System#2]
how does the permission system work? because everyone on the server can see an open ticket ...

**Comment by Cainify** [comment]
Hi NiceATC, 

The ticket system requires a premade category with preset permissions. It will then clone the permissions from the category and add the user to the ticket!

In a future update, I am thinking of pre-assigning the Everyone permissions per ticket! so all you would need to do is configure what groups will get what permissions via the category!

Cain!
